# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7d90bcdf99c9428d33dfaf60d6180f51"
name = "chatbot"
handle = "chatbot-242"
application_url = "https://chatbot-production-48d8.up.railway.app"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "customer_read_customers,customer_read_orders,customer_read_store_credit_account_transactions,customer_read_store_credit_accounts,read_orders,read_products,unauthenticated_read_product_listings,write_orders,write_products"

[auth]
redirect_urls = [
  "https://chatbot-production-48d8.up.railway.app/auth/callback",
  "https://chatbot-production-48d8.up.railway.app/api/auth/callback"
]

[pos]
embedded = false

[mcp.customer_authentication]
redirect_uris = [ "https://chatbot-production-48d8.up.railway.app/callback" ]
